### ISSUE TITLE
Warning: this app deletes all document revisions for all apps in the System

### ISSUE THREAD

**Issue by bomberstudios** [yo-op/sketchcachecleaner#1]
You're doing `rm -rf /.DocumentRevisions-V100`, which basically destroys any revision of any document from any app in the whole operating system.

Also, there are reports about unexpected side effects on the system (crashes, slowdowns) after removing the contents of that folder.

You should make that clearer in the app description and maybe show a warning when running the app.

**Comment by minikin** [comment]
Good point. 
I've just update README and going to add warning later today.
Thank you for the report.
