### ISSUE TITLE
Sketch Cache Cleaner Quits unexpectedly on macOS Catalina

### ISSUE THREAD

**Issue by RacketStack** [yo-op/sketchcachecleaner#10]
**Describe the bug**
when i open the app it shows sketch cache cleaner quit unexpectedly

**To Reproduce**
1.Open the Sketch Cache Cleaner 
2.And see the error

**Expected behavior**
I expect the app to be opened first and it should clean my sketch cache on auto save. 

**Screenshots**
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/42007333/70374274-a9fb1200-1916-11ea-85f2-0afec3b573ed.png">

**Desktop 
 - OS: macOS Catalina 
 - Version: 10.15

**Additional context**
I have installed the previous versions of this app and it doesn't shows any response it just asks password and it says all the files have been cleaned , I cannot see any difference after running the app the previous versions also

**Comment by minikin** [comment]
@RacketStack Thank you very much for the report! 
I'll try to reproduce and fix it at the of the week.

**Comment by ydnikolaev** [comment]
any updates here?
get the same

**Comment by minikin** [comment]
@ydnikolaev  I can't reproduce it.

**Comment by ydnikolaev** [comment]
@minikin 
hmmm
while v1.0.6b just suddenly close on start,
v1.0.5 seems to work for me

**Comment by frankparadiso** [comment]
@minikin same problem here.
v 1.0.6b crash at start, as reported by @RacketStack, and v 1.0.5 doesn't crash but I can't say it works, because I don't see the  confirmation mark at the end of the work. Any updates or idea?
Thank you

**Comment by DimLyamin** [comment]
@minikin Hello, now there is a mac os Catalina 10.15.4 system when opening the application, an application error occurs
<img width="422" alt="image" src="https://user-images.githubusercontent.com/63287750/78650794-77672300-78d0-11ea-963a-b8ecfcf40f89.png">

**Comment by minikin** [comment]
Thanks for the reports. I'll have a look as soon as will have time.

**Comment by minikin** [comment]
Just a quick update. I'll release a new version at the beginning of May. Thanks for your patience.

**Comment by MajidCS** [comment]
it's work with this code

`xattr -cr /Applications/Sketch.app
codesign --force --deep --sign - /Applications/Sketch.app `

**Comment by minikin** [comment]
Potentially fixed at #13
