### ISSUE TITLE
Do I need a paid apple dev account?

### ISSUE THREAD

**Issue by mattgfueled** [yo-op/sketchcachecleaner#14]
Cannot build the app in xcode
<img width="631" alt="error" src="https://user-images.githubusercontent.com/10068898/113923207-f7de8f00-9783-11eb-8846-8fef978a00aa.png">

**Comment by mill3rtime** [comment]
![Uploading cert.png…]()

**Comment by mill3rtime** [comment]
<img width="840" alt="cert" src="https://user-images.githubusercontent.com/10068898/113923603-6de2f600-9784-11eb-80da-02851a4ec23f.png">
