### ISSUE TITLE
The application can't be opened

### ISSUE THREAD

**Issue by uzikone** [yo-op/sketchcachecleaner#2]
Hey thank you for such amazing app, but I have some issue with run it on my Mac.
Got this error when trying to run the application. 
OS X 10.11.6
https://www.dropbox.com/s/rrv7lu2rdliaoiv/Screenshot%202017-07-12%2009.59.43.png?dl=0

**Comment by minikin** [comment]
Could you try to run [this build](https://www.dropbox.com/s/vlfjmu1cqxekhx5/Sketch%20Cache%20Cleaner_v1.01_test.app.zip?dl=1), please?

**Comment by podrivo** [comment]
Had the same issue. Build 1.01 worked for me.

**Comment by gunnzolder** [comment]
Sierra 10.12.6 Beta (16G24b), same issue, build 1.01 worked

**Comment by minikin** [comment]
Fix in https://github.com/yo-op/sketchcachecleaner/commit/d0cf596c9a2c3f13be1648479a255b8a414a4ef2. Thanks for reports!
